// AUTO-GENERATED by .github/workflows/social-images-sync.yml — do not edit manually.
// Run the workflow via Actions → "Sync Social Images to CDN" → "Run workflow" to update.
export const socialImages = {
  homepage: 'https://www.stpetemusic.live/images/hero/SPM-hero.webp',
  about:    'https://www.stpetemusic.live/images/og/about-bg2.png',
  events:   'https://www.stpetemusic.live/images/og/events-bg2.png',
  discover: 'https://www.stpetemusic.live/images/og/discover-bg2.png',
  live:     'https://www.stpetemusic.live/images/og/live-bg2.png',
  venues:   'https://www.stpetemusic.live/images/og/venues-bg2.png',
  tickets:  'https://www.stpetemusic.live/images/og/tickets-bg2.png',
} as const;

export type SocialImageKey = keyof typeof socialImages;
