// AUTO-GENERATED by .github/workflows/social-images-sync.yml — do not edit manually.
// Run the workflow via Actions → "Sync Social Images to CDN" → "Run workflow" to update.
export const socialImages = {
  about: 'https://cdn.stpetemusic.live/social/about-header-b4e4c17d.png',
  discover: 'https://cdn.stpetemusic.live/social/discover-header-4109dd3f.png',
  events: 'https://cdn.stpetemusic.live/social/events-header-d5660387.png',
  homepage: 'https://cdn.stpetemusic.live/social/homepage-header-87794b1c.png',
  live: 'https://cdn.stpetemusic.live/social/live-header-4f722876.png',
  tickets: 'https://cdn.stpetemusic.live/social/tickets-header-586a4e44.png',
  venues: 'https://cdn.stpetemusic.live/social/venues-header-d733da87.png',
} as const;

export type SocialImageKey = keyof typeof socialImages;
