// AUTO-GENERATED by .github/workflows/social-images-sync.yml — do not edit manually.
// Run the workflow via Actions → "Sync Social Images to CDN" → "Run workflow" to update.
export const socialImages = {
  about: 'https://cdn.stpetemusic.live/social/about-header-b94f02b2.png',
  discover: 'https://cdn.stpetemusic.live/social/discover-header-70c7de74.png',
  events: 'https://cdn.stpetemusic.live/social/events-header-542b322d.png',
  homepage: 'https://cdn.stpetemusic.live/social/homepage-header-87794b1c.png',
  live: 'https://cdn.stpetemusic.live/social/live-header-949e782d.png',
  tickets: 'https://cdn.stpetemusic.live/social/tickets-header-586a4e44.png',
  venues: 'https://cdn.stpetemusic.live/social/venues-header-453ab4b3.png',
} as const;

export type SocialImageKey = keyof typeof socialImages;
