name: OpenTofu Apply

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
  workflow_dispatch:  # allows manual trigger from GitHub Actions UI

permissions:
  contents: read

jobs:
  tofu-apply:
    name: Apply
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: infrastructure

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: '~1.9'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37  # v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: OpenTofu Init
        run: tofu init -backend-config="profile="

      - name: OpenTofu Apply
        run: tofu apply -auto-approve -input=false
        env:
          TF_VAR_github_token:       ${{ secrets.GH_TOKEN_AMPLIFY }}
          TF_VAR_listmonk_username:  ${{ secrets.LISTMONK_USERNAME }}
          TF_VAR_listmonk_password:  ${{ secrets.LISTMONK_PASSWORD }}
